apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 20s
      external_labels:
        deploy: test
        env: test
    rule_files:
    - /rules/*.yml
    alerting:
      alertmanagers:
      - path_prefix: /alertmanager/
        static_configs:
        - targets:
          - alertmanager:9093
    scrape_configs:
    - job_name: node
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - "172.31.11.252:9100"
      relabel_configs:  
      - source_labels: [__address__]
        regex: (.*):9100
        target_label: instance
        replacement: $1
        action: replace
    - job_name: redis
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - "172.31.11.252:9121"
      relabel_configs:
      - source_labels: [__address__]
        regex: (.*):9121
        target_label: instance
        replacement: $1
        action: replace 
