---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-system
  labels:
    k8s-app: kibana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
    srv: srv-kibana
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kube-system
  labels:
    k8s-app: kibana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    srv: srv-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana
  template:
    metadata:
      labels:
        k8s-app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.io/kubeimages/kibana:7.9.3
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch-logging:9200
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: SERVER_BASEPATH
            value: "/kibana"
          - name: SERVER_PUBLICBASEURL
            value: "http://43.206.157.95:32537/kibana"
          - name: SERVER_REWRITEBASEPATH
            value: "true"
          - name: SERVER_CORS_ENABLED
            value: "true"
          - name: SERVER_CORS_ALLOWCREDENTIALS
            value: "false"
          - name: SERVER_NAME
            value: "kibana"
          - name: XPACK_REPORTING_ENABLED
            value: "false"
          - name: XPACK_SECURITY_ENABLED
            value: "false"
          - name: NODE_OPTIONS
            value: --max-old-space-size=1800
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
