---
# Source: elastalert2/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastalert2
  namespace: kube-system
  labels:
    app.kubernetes.io/name: elastalert2
    helm.sh/chart: elastalert2-2.9.0
    app.kubernetes.io/instance: elastalert2
    app.kubernetes.io/managed-by: Helm
